### ISSUE TITLE
config to pass loadbalancer IP to envoy

### ISSUE THREAD

**Issue by afewell** [afewell/ovathetap#62]

**Comment by afewell** [comment]
create secret with loadbalancer ip value and update tap-values config as needed to pass value so envoy svc gets configured correctly on deployment

**Comment by afewell** [comment]
in tap-values:
```
package_overlays:
  - name: contour
    secrets:
    - name: "contour-external-ips-overlay-secret"
```
secret yaml:
apiVersion: v1
kind: Secret
metadata:
  name: contour-external-ips-overlay-secret
  namespace: tap-install
stringData:
  patch.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"kind":"Service","metadata":{"namespace":"tanzu-system-ingress", "name":"envoy"}})
    ---
    spec:
      #@overlay/match missing_ok=True
      externalIPs: ["192.168.49.2"]
