### ISSUE TITLE
harbor nodeport problems?

### ISSUE THREAD

**Issue by afewell** [afewell/ovathetap#73]

**Comment by afewell** [comment]
for some unknown reason in current test, harbor helm chart is deploying without any nodeport or other accessible service, even with values file specifying nodeport. I did also compare values with other currently running recent harbor deployment and it did deploy the nodeport service. 

I looked through the configs several times, maybe there is some mistake but none I could find, this could be a bug. I am not specifying versions of harbor or the helm chart, and while I did verify the helm chart manifest didnt change, could still be bugs between differing harbor and chart versions. 

attempting to implement harbor service manifest pulled from a working implementation rather than troubleshooting further:
```
apiVersion: v1
kind: Service
metadata:
  labels:
  name: harbor
  namespace: harbor
spec:
  ports:
  - name: https
    nodePort: 30003
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: notary
    nodePort: 30004
    port: 4443
    protocol: TCP
    targetPort: 4443
  selector:
    app: harbor
    component: nginx
    release: harbor
  sessionAffinity: None
  type: NodePort
```
